import { useEffect, useMemo, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

// Default placeholder model (generated by scripts/generate-machine-glb.mjs)
import machineUrl from '../models/machine.glb?url'

// Model now accepts a dynamic `modelUrl` so desktop uploads or remote URLs can be used.
export default function Model({ modelUrl, activeAnimation, onAnimationNames }) {
  const group = useRef()
  // Prefer provided modelUrl, fall back to bundled machineUrl
  const url = modelUrl || machineUrl
  const gltf = useGLTF(url)
  const { actions, names } = useAnimations(gltf.animations, group)

  const stableNames = useMemo(() => names ?? [], [names])

  useEffect(() => {
    onAnimationNames?.(stableNames)
  }, [onAnimationNames, stableNames])

  useEffect(() => {
    if (!actions) return

    // Stop everything before playing the next clip.
    for (const key of Object.keys(actions)) {
      actions[key]?.stop()
    }

    if (!activeAnimation) return

    const next = actions[activeAnimation]
    if (!next) return

    next.reset()
    next.fadeIn(0.12)
    next.play()

    return () => {
      next.fadeOut(0.12)
    }
  }, [actions, activeAnimation])

  return (
    <group ref={group} position={[0, 0, -1.5]} scale={1}>
      <primitive object={gltf.scene} />
    </group>
  )
}

useGLTF.preload(machineUrl)
