import { useEffect, useMemo, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

// Note: this asset is generated by scripts/generate-machine-glb.mjs by default.
// Replace src/models/machine.glb with your real model to get your real clips.
import machineUrl from '../models/machine.glb?url'

export default function Model({ activeAnimation, onAnimationNames }) {
  const group = useRef()
  const gltf = useGLTF(machineUrl)
  const { actions, names } = useAnimations(gltf.animations, group)

  const stableNames = useMemo(() => names ?? [], [names])

  useEffect(() => {
    onAnimationNames?.(stableNames)
  }, [onAnimationNames, stableNames])

  useEffect(() => {
    if (!actions) return

    // Stop everything before playing the next clip.
    for (const key of Object.keys(actions)) {
      actions[key]?.stop()
    }

    if (!activeAnimation) return

    const next = actions[activeAnimation]
    if (!next) return

    next.reset()
    next.fadeIn(0.12)
    next.play()

    return () => {
      next.fadeOut(0.12)
    }
  }, [actions, activeAnimation])

  return (
    <group ref={group} position={[0, 0, -1.5]} scale={1}>
      {/*
        XR-specific decision:
        - Place the model ~1.5m in front of the user (negative Z) so it appears immediately
          in view when entering immersive VR.
      */}
      <primitive object={gltf.scene} />
    </group>
  )
}

useGLTF.preload(machineUrl)
